### ISSUE TITLE
Fix JavaDoc errors

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-gmlgeox#15]
Currently there are about 40 errors that avoid the creation of a readable JavaDoc.

@jechterhoff hope it's OK for you when I remove the angle brackets (-or should I replace it with something else)?
```
ValidationUtil.java:12: error: unknown tag: at
 * @author Johannes Echterhoff (echterhoff <at> interactive-instruments
ValidationUtil.java:13: error: unknown tag: dot
 *         <dot> de)
```

**Comment by jechterhoff** [comment]
Go ahead :-)
