### ISSUE TITLE
Support geometries with 3 dimensional CRS 

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-gmlgeox#19]
Commit ref https://github.com/interactive-instruments/etf-gmlgeox/commit/88c139a418a6326f263dc65787a5cba346bddf27.

Requirement is based on an issue in the ETS repository inspire-eu-validation/ets-repository#51.

Current status: version 1.1.2 contains possibly a memory hole. ETF will continue to use version 1.1.0.

**Comment by jonherrmann** [comment]
https://github.com/interactive-instruments/etf-gmlgeox/commit/580055f3257f62c19712304bb13c338430f6cf00 supports 3D geometries, but the performance will be poor as long as the degree core is part of GmlGeoX.

We must redesign GmlGeoX and the Basex test driver, so that the CRS manager is not re-initialized for each new test run.

**Comment by jonherrmann** [comment]
Ref https://github.com/interactive-instruments/etf-bsxtd/commit/aa02091cf5ed8eed85f4f84d7caec76c15e0c9e7

**Comment by cportele** [comment]
The INSPIRE assertion gmlas.d.10 works correctly now (ggeo:validateAndReport), but gmlas.d.11. (ggeo:index) still report messages like `XML document 'au-3d-1-0.xml', AdministrativeBoundary 'ID.3.2': The feature geometry is not a valid GML geometry: class org.deegree.commons.xml.XMLParsingException: Error in XML document (line: 2, column: 37, character offset: 751): Cannot parse 'gml:posList': contains 9 values, but coordinate dimension is 2. This does not match.` for a geometry with a 3D CRS.

**Comment by jonherrmann** [comment]
I have implemented a unit test in the bsxtd test driver and used the au-3d-1-0.xml test file. All issues have been reported correctly. The unit test result looks similar to this [one](http://demo-snapshot.etf-validator.net/etf-webapp/v2/TestRuns/EID399db5fa-61e0-4c32-94d5-d642519375e5.html?lang=en#EIDe4699879-cb59-4220-af7a-06aa6bf2215b).

When I run the test file with the [INSPIRE GML application schemas test suite](http://demo-snapshot.etf-validator.net/etf-webapp/#start-tests?ids=EID09820daf-62b2-4fa3-a95f-56a0d2b7c4d8), I can see the error [messages](http://demo-snapshot.etf-validator.net/etf-webapp/v2/TestRuns/EIDc0b0258f-42c0-4425-9284-43a15cec8ba3.html?lang=en#EID741e5b19-1037-4b27-ba10-50211bd19c23).

In the first ETS, the `ggeo:validateAndReport` function has been used directly. In the second ETS the issues are reported by the [`ggeo:index` function](https://github.com/inspire-eu-validation/ets-repository/blob/master/testquery.xq#L459).

We should add a [unit test](https://github.com/interactive-instruments/etf-gmlgeox/blob/next/src/test/resources/queries/test_geometry_3d.xq) with the ggeo:index function in the GmlGeoX module.

**Comment by jonherrmann** [comment]
need to be further tested
